CREATE TABLE poop_monitoring
(
    id                       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    stool_composition        INTEGER                                  NOT NULL,
    quantity                 INTEGER                                  NOT NULL,
    feeling                  INTEGER                                  NOT NULL,
    has_excessive_flatulence BOOLEAN                                  NOT NULL,
    has_pain                 BOOLEAN                                  NOT NULL,
    has_abdominal_bloating   BOOLEAN                                  NOT NULL,
    has_mucus                BOOLEAN                                  NOT NULL,
    has_food_residue         BOOLEAN                                  NOT NULL,
    has_colic                BOOLEAN                                  NOT NULL,
    has_unusual_smells       BOOLEAN                                  NOT NULL,
    pooping_number           INTEGER                                  NOT NULL,
    user_id                  INTEGER                                  NOT NULL,
    CONSTRAINT pk_poop_monitoring PRIMARY KEY (id)
);

ALTER TABLE poop_monitoring
    ADD CONSTRAINT FK_POOP_MONITORING_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);