CREATE TABLE food
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    category INTEGER                                  NOT NULL,
    quantity DOUBLE PRECISION                         NOT NULL,
    measure  INTEGER                                  NOT NULL,
    brand    VARCHAR(255),
    user_id  INTEGER                                  NOT NULL,
    CONSTRAINT pk_food PRIMARY KEY (id)
);

ALTER TABLE food
    ADD CONSTRAINT FK_FOOD_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);