CREATE TABLE health
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    psychological_state INTEGER                                  NOT NULL,
    physical_dolor      INTEGER                                  NOT NULL,
    user_id             INTEGER                                  NOT NULL,
    CONSTRAINT pk_health PRIMARY KEY (id)
);

CREATE TABLE sleep
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    period BYTEA,
    quality   INTEGER                                  NOT NULL,
    health_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_sleep PRIMARY KEY (id)
);

CREATE TABLE sport
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    period BYTEA,
    intensity INTEGER                                  NOT NULL,
    health_id INTEGER                                  NOT NULL,
    CONSTRAINT pk_sport PRIMARY KEY (id)
);

ALTER TABLE health
    ADD CONSTRAINT FK_HEALTH_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE sleep
    ADD CONSTRAINT FK_SLEEP_ON_HEALTH FOREIGN KEY (health_id) REFERENCES health (id);

ALTER TABLE sport
    ADD CONSTRAINT FK_SPORT_ON_HEALTH FOREIGN KEY (health_id) REFERENCES health (id);